#! /bin/bash

# Archer Arrow
# NAME: Containers
# DESC: Setup containers with podman and distrobox

# https://docs.podman.io/en/latest/Commands.html
# https://docs.podman.io/en/latest/markdown/podman-exec.1.html

show_info "Installing container packages"
paru -Syu
paru -S --needed podman podman-compose distrobox

show_info "Configuring podman"
sudo touch /etc/subuid /etc/subgid
sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 "$USER"
sudo cp -r /usr/share/containers/ /etc/containers/

podman system migrate
sudo systemctl enable --now podman-restart.service

# Install Kontainer if Flatpak is available
if pacman -Q flatpak &>/dev/null; then
    show_info "Installing Kontainer"
    flatpak install --system --assumeyes --noninteractive flathub io.github.DenysMb.Kontainer
fi