#! /bin/bash

# Archer Arrow
# NAME: Flatpak
# DESC: Setup Flatpaks with KDE integration

show_info "Installing flatpak packages"
paru -Syu
paru -S --needed flatpak flatpak-kcm discover xdg-desktop-portal-kde

echo -e "Fix game controller remote access pop up spam in KDE Plasma"
flatpak permission-set kde-authorized remote-desktop "" yes
