#! /bin/bash

# Archer Arrow
# NAME: Virtualization
# DESC: Setup and manage VMs using Virt-Manager

current_user=$USER

sudo echo

show_info "Installing virtualization packages"
paru -S --needed libvirt qemu-base virt-manager virt-viewer dnsmasq

show_info "Configuring libvirt"
sudo systemctl enable --now libvirtd
sudo usermod -aG libvirt "$current_user"

if sudo virsh net-list --all | grep -q "default.*active"; then
    echo "Network default already active"
else
    sudo virsh net-start default
fi
sudo virsh net-autostart default

echo -e "Checking CPU"
lscpu_output=$(lscpu)
read -r -t 1

if [[ $lscpu_output == *"AuthenticAMD"* ]]; then
	echo -e "Adding AMD kernel parameters to GRUB"
	sudo sed -i "s/\(GRUB_CMDLINE_LINUX_DEFAULT=\"[^\"]*\)\"/\1 amd_iommu=on iommu=pt\"/" /etc/default/grub

elif [[ $lscpu_output == *"GenuineIntel"* ]]; then
	echo -e "Adding Intel kernel parameters to GRUB"
	sudo sed -i "s/\(GRUB_CMDLINE_LINUX_DEFAULT=\"[^\"]*\)\"/\1 intel_iommu=on iommu=pt\"/" /etc/default/grub
fi

echo -e "Rebuilding GRUB configs"
sudo grub-mkconfig -o /boot/grub/grub.cfg
